[package]
name = "mj-lstm"
version = "0.1.0"
authors = ["Mikko Juola <mikjuo@gmail.com>"]
edition = "2018"

[dependencies]
rcmaes = { git = "https://github.com/Noeda/rcmaes", rev = "4358389986d929dd633c9d36cc33d41eeb8e60c8" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.7"
statrs = "0.15"

[dev-dependencies]
quickcheck = "0.9"
criterion = "0.3"
crossbeam = "0.7"
num_cpus = "1"

[profile.release]
opt-level = 3
overflow-checks = false
lto = true

[[bench]]
path = "src/benches/benchmark.rs"
name = "benchmark"
harness = false

[[bench]]
path = "src/benches/flops_benchmark.rs"
name = "flops_benchmark"
harness = false
