[package]
name = "mj-lstm"
version = "0.1.0"
authors = ["Mikko Juola <mikjuo@gmail.com>"]
edition = "2018"

[dependencies]
rcmaes = { git = "https://github.com/Noeda/rcmaes" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.7"

[dev-dependencies]
quickcheck = "0.9"
criterion = "0.3"

[profile.release]
opt-level = 3
overflow-checks = false
lto = true

[[bench]]
path = "src/benches/benchmark.rs"
name = "benchmark"
harness = false
